# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b70e04985acfed5320a214c9e68bc2848e1156c91bd108458c32eb1053d43e53733c4f2c70cdb619aad5fde0d3038d87b262b0b542d01379a8441c1d075fddf

test:
  secret_key_base: d09eabf4a8bde9ecdb043fe8bbecef210293837d83f046a9415351f05b1078f142e31a54ab2c6aa18741459111502d7a404fbc86573cbdb079b30e44eeac280d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
